#!/usr/bin/env bash

set -euo pipefail

SERVICE_NAME="${SERVICE_NAME:-eagle-mqtt-bridge}"
USER_SYSTEMD_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
SERVICE_FILE="${USER_SYSTEMD_DIR}/${SERVICE_NAME}.service"
ENV_FILE="${USER_SYSTEMD_DIR}/${SERVICE_NAME}.env"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_SCRIPT="${REPO_DIR}/build.sh"
RUN_SCRIPT="${REPO_DIR}/run.sh"

required_vars=(
  MQTT_HOST
  EAGLE_HOST
  EAGLE_USER
  EAGLE_PASS
)

optional_vars=(
  MQTT_TOPIC
  MQTT_USER
  MQTT_PASS
  LOG_LEVEL
  EAGLE_POLL_INTERVAL_MS
  AVAILABILITY_TIMEOUT_MS
  EAGLE_FAILURES_BEFORE_OFFLINE
)

if [[ ! -x "${BUILD_SCRIPT}" ]]; then
  echo "Expected executable build script at ${BUILD_SCRIPT}"
  exit 1
fi

if [[ ! -x "${RUN_SCRIPT}" ]]; then
  echo "Expected executable run script at ${RUN_SCRIPT}"
  exit 1
fi

for var_name in "${required_vars[@]}"; do
  if [[ -z "${!var_name:-}" ]]; then
    echo "${var_name} is required."
    exit 1
  fi
done

if [[ -n "${MQTT_USER:-}" && -z "${MQTT_PASS:-}" ]]; then
  echo "MQTT_PASS is required when MQTT_USER is set."
  exit 1
fi

if [[ -z "${MQTT_USER:-}" && -n "${MQTT_PASS:-}" ]]; then
  echo "MQTT_USER is required when MQTT_PASS is set."
  exit 1
fi

write_export() {
  local var_name="$1"
  local value="${!var_name:-}"
  printf "export %s=%q\n" "${var_name}" "${value}"
}

tmp_env="$(mktemp)"
tmp_service="$(mktemp)"
trap 'rm -f "${tmp_env}" "${tmp_service}"' EXIT

mkdir -p "${USER_SYSTEMD_DIR}"

{
  echo "# Generated by install-systemd-service.sh"
  for var_name in "${required_vars[@]}"; do
    write_export "${var_name}"
  done
  for var_name in "${optional_vars[@]}"; do
    if [[ -n "${!var_name:-}" ]]; then
      write_export "${var_name}"
    fi
  done
} > "${tmp_env}"

cat > "${tmp_service}" <<EOF
[Unit]
Description=Rainforest Eagle to MQTT bridge
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=${REPO_DIR}
Environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ExecStart=/bin/bash -lc 'source "${ENV_FILE}"; exec "${RUN_SCRIPT}"'
Restart=always
RestartSec=10

[Install]
WantedBy=default.target
EOF

install -m 600 "${tmp_env}" "${ENV_FILE}"
install -m 644 "${tmp_service}" "${SERVICE_FILE}"

"${BUILD_SCRIPT}"

systemctl --user daemon-reload
systemctl --user enable --now "${SERVICE_NAME}.service"

echo "Installed ${SERVICE_NAME}.service"
echo "Environment file: ${ENV_FILE}"
echo "Check status with: systemctl --user status ${SERVICE_NAME}.service"

if loginctl show-user "${USER}" -p Linger 2>/dev/null | grep -Fq "Linger=yes"; then
  echo "User lingering is enabled, so the service should also start on boot."
else
  echo "User lingering is not enabled."
  echo "This service will restart automatically while your user systemd instance is running."
  echo "To also start on boot before login, an admin must run:"
  echo "  sudo loginctl enable-linger ${USER}"
fi
